# Generated by Django 4.2.4 on 2023-10-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_output')),
                ('vehicle_id', models.IntegerField()),
                ('license_plate_ocr_text', models.CharField(max_length=255)),
                ('license_plate_conf_score', models.FloatField()),
                ('vehicle_bbox', models.CharField(max_length=255)),
                ('license_plate_bbox', models.CharField(max_length=255)),
                ('license_plate_cropped_image', models.ImageField(upload_to='image_output')),
            ],
        ),
    ]
