# Generated by Django 4.2.4 on 2023-10-03 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mca_project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
