# Generated by Django 4.2.4 on 2023-10-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mca_project_app', '0002_detectimage_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectimage',
            name='vehicle_id',
        ),
    ]
