# Generated by Django 4.2.4 on 2023-10-05 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mca_project_app', '0003_remove_detectimage_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectimage',
            name='detected_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detectimage',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='detectimage',
            name='license_plate_cropped_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
