# Generated by Django 4.2.4 on 2023-10-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_project_app', '0004_detectimage_detected_image_alter_detectimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectimage',
            name='detected_image',
        ),
        migrations.AlterField(
            model_name='detectimage',
            name='image',
            field=models.ImageField(upload_to='image_output'),
        ),
        migrations.AlterField(
            model_name='detectimage',
            name='license_plate_cropped_image',
            field=models.ImageField(upload_to='image_output'),
        ),
    ]
