# Generated by Django 4.2.4 on 2023-10-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_project_app', '0006_rename_image_detectimage_original_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('frame_number', models.IntegerField()),
                ('processed_video', models.ImageField(upload_to='video_output')),
                ('license_plate_ocr_text', models.CharField(max_length=255)),
                ('license_plate_conf_score', models.FloatField()),
                ('vehicle_bbox', models.CharField(max_length=255)),
                ('license_plate_bbox', models.CharField(max_length=255)),
                ('license_plate_cropped_image', models.ImageField(upload_to='video_output')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
