# Generated by Django 4.2.4 on 2023-10-14 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mca_project_app', '0007_detectvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectvideo',
            name='frame_number',
        ),
    ]
