# Generated by Django 4.2.4 on 2023-10-14 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mca_project_app', '0008_remove_detectvideo_frame_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectvideo',
            options={'verbose_name': 'Video Detection Result', 'verbose_name_plural': 'Video Detection Results'},
        ),
        migrations.RemoveField(
            model_name='detectvideo',
            name='video_name',
        ),
        migrations.AddField(
            model_name='detectvideo',
            name='original_video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='video_input', verbose_name='Original Video File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detectvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='detectvideo',
            name='license_plate_bbox',
            field=models.CharField(max_length=255, verbose_name='License Plate Bounding Box'),
        ),
        migrations.AlterField(
            model_name='detectvideo',
            name='license_plate_conf_score',
            field=models.FloatField(verbose_name='License Plate Confidence Score'),
        ),
        migrations.AlterField(
            model_name='detectvideo',
            name='license_plate_cropped_image',
            field=models.ImageField(upload_to='video_output', verbose_name='Cropped License Plate Image'),
        ),
        migrations.AlterField(
            model_name='detectvideo',
            name='license_plate_ocr_text',
            field=models.CharField(max_length=255, verbose_name='License Plate OCR Text'),
        ),
        migrations.AlterField(
            model_name='detectvideo',
            name='processed_video',
            field=models.FileField(upload_to='video_output', verbose_name='Processed Video File'),
        ),
        migrations.AlterField(
            model_name='detectvideo',
            name='vehicle_bbox',
            field=models.CharField(max_length=255, verbose_name='Vehicle Bounding Box'),
        ),
    ]
