# Generated by Django 4.2.4 on 2023-10-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_project_app', '0009_alter_detectvideo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectvideo',
            name='license_plate_cropped_image',
            field=models.ImageField(upload_to='output_results_videos', verbose_name='Cropped License Plate Image'),
        ),
        migrations.AlterField(
            model_name='detectvideo',
            name='original_video',
            field=models.FileField(upload_to='output_results_videos', verbose_name='Original Video File'),
        ),
        migrations.AlterField(
            model_name='detectvideo',
            name='processed_video',
            field=models.FileField(upload_to='output_results_videos', verbose_name='Processed Video File'),
        ),
    ]
