# Generated by Django 4.2.4 on 2023-10-28 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mca_project_app', '0010_alter_detectvideo_license_plate_cropped_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate_ocr_text', models.CharField(max_length=255)),
                ('license_plate_conf_score', models.FloatField()),
                ('vehicle_bbox', models.CharField(max_length=255)),
                ('license_plate_bbox', models.CharField(max_length=255)),
                ('license_plate_cropped_image', models.ImageField(upload_to='image_output')),
                ('detect_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mca_project_app.detectimage')),
            ],
        ),
    ]
