# Generated by Django 4.2.4 on 2023-10-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mca_project_app', '0011_licenseplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LicensePlate',
        ),
    ]
