# Generated by Django 4.2.4 on 2023-11-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_project_app', '0012_delete_licenseplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_video', models.FileField(upload_to='output_results_camera', verbose_name='Original Video File')),
                ('processed_video', models.FileField(upload_to='output_results_camera', verbose_name='Processed Video File')),
                ('license_plate_ocr_text', models.CharField(max_length=255, verbose_name='License Plate OCR Text')),
                ('license_plate_conf_score', models.FloatField(verbose_name='License Plate Confidence Score')),
                ('vehicle_bbox', models.CharField(max_length=255, verbose_name='Vehicle Bounding Box')),
                ('license_plate_bbox', models.CharField(max_length=255, verbose_name='License Plate Bounding Box')),
                ('license_plate_cropped_image', models.ImageField(upload_to='output_results_camera', verbose_name='Cropped License Plate Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Camera Detection Result',
                'verbose_name_plural': 'Camera Detection Results',
            },
        ),
    ]
