# Generated by Django 4.2.4 on 2023-11-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mca_project_app', '0013_detectcamera'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectcamera',
            options={},
        ),
    ]
